order_link= "xpath@@//li[@class='pushy-link']/a[@href='/order'][contains(text(),'ORDER')]"
tracker_link = "xpath@@//li[@class='pushy-link']/a[@href='/tracker'][contains(text(),'TRACKER')]"
ship_cookies_link ="xpath@@//li[@class='pushy-link']/a[contains(text(),'SHIP COOKIES')]"
gift_card_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'GIFT CARDS')]"
gear_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'GEAR')]"
menu_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'MENU')]"
catering_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'CATERING')]"
events_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'EVENTS')]"
locations_link ="xpath@@//li[@class='pushy-link']/a[contains(text(),'LOCATIONS')]"
about_us_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'ABOUT US')]"
loyalty_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'LOYALTY')]"
contact_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'CONTACT')]"
login_link = "xpath@@//li[@class='pushy-link']/a[contains(text(),'LOGIN')]"