add_more_items = "xpath@@//button[@id='add-more-items']"
add_to_order="xpath@@//button[contains(text(),'Add to Order')]"
select_flavours = "xpath@@//select[@id='up-sell-flavors']"
full_name_input= "xpath@@//input[@id='recipient-name']"
phone_number_input = "xpath@@//input[@id='recipient-phone']"
extension_input = "xpath@@//input[@id='recipient-phone-extension']"
secondary_address_input= "xpath@@//input[@id='recipient-address-2']"
deliver_to_my_door_chkbx="xpath@@//input[@id='no-contact-delivery-option1']"
meet_me_outside_chkbx="xpath@@//input[@id='no-contact-delivery-option2']"
leave_order_at_door_chkbx = "xpath@@//input[@id='no-contact-delivery-option3']"
delivery_message_input= "xpath@@//textarea[@id='instructions']"
recipient_message_input= "xpath@@//textarea[@id='comments']"