current_user_email = "xpath@@//input[@id='email']"
current_password = "xpath@@//form[@id='login-form']/div/input[@name='password']"
remember_me_chkbx= "Xpath@@//form[@id='login-form']/div/div/input[@name='remember_me']"
login_btn= "xpath@@//button[@id='login-btn']"
forgot_pwd= "xpath@@//div/a[contains(text(),'Forgot your password?')]"
register_email= "xpath@@//input[@id='email-register']"
register_password ="xpath@@//form[@id='register-form']/div/input[@name='password']"
confirm_password= "xpath@@//form[@id='register-form']/div/input[@id='password-confirm']"
captcha_chkbx="xpath@@//span[@id='recaptcha-anchor']"
create_account_btn = "xpath@@//button[@id='submit-register-form']"
no_loyalty_program = "xpath@@//input[@id='no_loyalty']"
like_emails = "xpath@@//input[@id='newsletter']"