add_more_items = "xpath@@//button[@id='add-more-items']"
add_to_order="xpath@@//button[contains(text(),'Add to Order')]"
select_flavours = "xpath@@//select[@id='up-sell-flavors']"
recipient_full_name_input= "xpath@@//input[@id='recipient-name']"
recipient_phone_number_input = "xpath@@//input[@id='recipient-phone']"
recipient_extension_input = "xpath@@//input[@id='recipient-phone-extension']"
recipient_secondary_address_input= "xpath@@//input[@id='recipient-address-2']"
deliver_to_my_door_chkbx="xpath@@//input[@id='no-contact-delivery-option1']"
meet_me_outside_chkbx="xpath@@//input[@id='no-contact-delivery-option2']"
leave_order_at_door_chkbx = "xpath@@//input[@id='no-contact-delivery-option3']"
delivery_message_input= "xpath@@//textarea[@id='instructions']"
recipient_message_input= "xpath@@//textarea[@id='comments']"
same_as_above_chkbx = "xpath@@//input[@id='copy-recipient']"
customer_full_name_input="xpath@@//input[@id='customer-name']"
customer_phone_number_input = "xpath@@//input[@id='customer-phone']"
customer_extenstion_input="xpath@@//input[@id='customer-phone-extension']"
customer_email_input= "xpath@@//div[@id='checkout-your-info-email']"
continue_as_guest_radio_btn = "xpath@@//input[@name='payment_guest'][@value= 'Nope']"
register_after_checkout_radio_btn ="xpath@@//input[@name='payment_guest'][@value= 'Register']"
already_registered_radio_btn = "xpath@@//input[@name='payment_guest'][@value= 'Already']"
credit_card_btn= "xpath@@//a[@id = 'pills-credit-tab']"
credit_card_name="xpath@@//input[@id='cc-name']"
credit_card_number= "xpath@@//input[@id='cc-number']"
credit_card_expiry="xpath@@//input[@id='cc-exp']"
credit_card_cvc="xpath@@//input[@id='cc-security-code']"
credit_card_postal_code= "xpath@@//input[@id='cc-zip']"
tip_dropdown="xpath@@//select[@id='payment-tip']"
place_order_btn ="xpath@@//button[@id='submit-order-btn']"
checkout_edit_time="xpath@@//div[@id='checkout-edit-time']"