input_first_name = "xpath@@//input[@name='firstname']"
input_last_name = "xpath@@//input[@name='lastname']"
input_email = "xpath@@//input[@name='user.email']"
input_phone_number = "xpath@@//input[@name='telephone']"
credit_card_chkbx = "xpath@@//input[@name='storecc']"
allow_notification_chkbx= "xpath@@//input[@name='allow_push_notifications']"
large_groups_chkbx= "xpath@@//input[@name='large_groups']"
event_groups_chkbx = "xpath@@//input[@name='event_offers']"
newsletter_chkbx = "xpath@@newsletter"
update_profile_btn = "xpath@@//button[contains(text(),'Update Profile')]"
input_current_pwd = "xpath@@//input[@name ='current_password']"
input_new_pwd = "xpath@@//input[@name ='new_password']"
input_confirm_pwd = "xpath@@//input[@name ='new_password_confirmation']"
update_pwd_btn = "xpath@@//button[contains(text(),'Update Password')]"