menu_btn= "xpath@@//a[@href='/user/menu']"
edit_profile = "xpath@@//a[@href='/user/profile']"
view_all_orders = "xpath@@//a[@href='/user']/ancestor::div[contains(text(),'Orders')]"
view_all_address_book = "xpath@@//a[@href='/user/addressBook']/ancestor::div[contains(text(),'Address Book')]"
view_all_credit_cards  = "xpath@@//a[@href='/user/cards']/ancestor::div[contains(text(),'Credit Cards')]"
view_loyalty = "xpath@@//a[@href='/loyalty']"
logout_link = "xpath@@//a[@href='/user/logout']"